name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/search-service/Chart.yaml
    secrets: inherit

  release:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    needs: semantic
    with:
      environment: prod
      chart_path: chart/search-service/Chart.yaml
    secrets: inherit
